apiVersion: v1
clusters:
- name: "dev-cluster"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EUXhOakUzTkRNME1Gb1hEVE0wTURReE5qRTNORE0wTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjE1CkwybTVwZldIQytWMmh2SjJBaWYrM1dUSHJISDB0TzBIMHBlaHZhbXphcXptUVcxQnVtKzNCSFFjNFNKemxHZ3cKSkV5VXNQMHF0MGJjVktiOHFmY0o3Z3l6TU1FaTlRdENnVWl5WE1GUmxSbElIL2lLZEM5V0lGelB4SE9uTm5lMwpxWkg3WlV0OGVzUEdiRlZVUU5ZTnMyQzhncFRGdHc3N2xsNjVRRHAzTEJKa2Vyc3hWc29CVlV2WSt0QXo0YUNqCnh3dVZ4UWxtUW95RWJsZjVUVmp5UlNsdE5weUdhTFdpWS9SMGEyU0dTK2pNbS9rQUliSkkvL1cwaWJoV0hEcFYKY1B6bDhNWXpwU0pnOStVMHc4RGx0dEZpcXVib1FaS2t3TFY5R1kxOXN5MnV1WDNEV2M0bTQ4MXVrZ1NYaHVVNwp3T0FQV3A1dE9FRmxOdU1iT2tFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGemRpL0hQZ3VIaHZRT29ucnVVclhPQi9yOFJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBVE5OWnhENm5HQlFZQzJhRlFHMWV4Wkkvenh1M3ZyOHd0cE1SQk5SbmlHMmdnL1AxNgpFNE5SakdJVnhIcXkrZTgvUFhZNldxNDBGT0xPUDRZc2o0SGVvMkhsVzdsYmYyTmtQdEJObDlON3NpSytNYWZ4Cnh1M3dGc25MSmRLMTYyM0sxOG9USXNJL2VNYjc3bWZzZEtUc1hObkRuZ1B3dEJWSkVvekNhajVhb0RnVW5CMHkKdDU0RlYzcGJ1NUdENmE5TFpKanF1alJSb2xaSmRWRTE3bHZvM1ltY2Z0WUZIbUMxaGNrdEw5UlF3QVJqcUY2YgptUW11WTNQZWtHTVc1VUN4ckFMOUIvb0dNZEpqcU1XSkxTeTk3U0p4TmorV29MV3dIdlIveFRlYTg5Y1EvN0ROCmZBbVJzUWkySE14cEFTeE1PbDJIQ3NGSjJPSjRLdTJ4SFBwbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://6f37c37e-9baa-4cf8-b5e6-73a69da1ea63.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@dev-cluster
  context:
    cluster: "dev-cluster"
    user: degit v-cluster-admin
current-context: admin@dev-cluster
kind: Config
preferences: {}
users:
- name: dev-cluster-admin
  user:
    token: ssCf7nwviGwlmrAm1PDFe6U4WmAh4Fa7OH4oAIXHlemFEJu1lOQwjDO3